routes:
  /: 
    data: page.veiled-productions
    template: homepage 

collections:
  /blog/:
    permalink: /{slug}/
    template: index
    data: page.blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
