routes:
  /: 
    data: page.veiled-productions
    template: homepage 

  /oxfordshire-wedding-video/:
    controller: channel
    template: county
    filter: tag:oxfordshire-wedding-video
    data: page.oxfordshire

collections:
  /blog/:
    permalink: /{slug}/
    template: index
    data: page.blog


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
